(use-package beacon
  :ensure t
  :defer t)
(use-package cdlatex
  :ensure t
  :defer t)
(use-package gnu-elpa-keyring-update
  :ensure t
  :defer t)
(use-package lua-mode
  :ensure t
  :defer t)
(use-package projectile
  :ensure t
  :defer t)
(use-package smex
  :ensure t
  :defer t)
(use-package sqlite3
  :ensure t
  :defer t)
(use-package yaml-mode
  :ensure t
  :defer t)

(provide 'install-packages)
